<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">All generated reports</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="<?php echo base_url('Admin')?>" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <a class="breadcrumb-item" href="#">-</a>
                <span class="breadcrumb-item active">Generated report</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body" style="border: thick #153505 solid;border-radius: 14px;">
        <h2 style="margin-top:0px">Reports List</h2>

        <div style="width:100%; max-width:100%; overflow-x:auto; overflow-y:hidden;">
        <table class="table table-bordered" id="data-table1" style="margin-bottom: 10px; min-width: 980px;">
            <thead>
            <tr>
                <th>No</th>
                <th>Report Type</th>
                <th>Status</th>
                <th>progress</th>
                <th>Download Link</th>
                <th>Generated Time</th>
                <th>Completed Time</th>

                <th>Generated By</th>

                <th>Action</th>
            </tr>
            </thead>
            <tbody>

          <?php
          $start = 0;
            foreach ($reports_data as $reports)
            {
                ?>
                <tr>
			<td width="80px" style="white-space: nowrap;"><?php echo ++$start ?></td>
                    <td style="word-break: break-word;"><?php echo $reports->report_type ?></td>
                    <td><?php   if($reports->status=='completed'){echo "<font color='green'>Complete</font>";}else{ echo "<font color='red'>In Progress</font>";} ?></td>
                    <td style="min-width: 150px;"><div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: <?php echo $reports->percentage ?>%;" aria-valuenow="<?php echo $reports->percentage ?>" aria-valuemin="0" aria-valuemax="100">

                            </div>
                        </div>
                        <?php echo round($reports->percentage,2) ?>%
                        </td>
                    <td style="white-space: nowrap;"><?php
<<<<<<< HEAD
                        $previewLink = report_preview_url($reports->download_link);
                        if ($previewLink) {
                            ?>
                            <a href="<?php echo htmlspecialchars($previewLink); ?>" target="_blank" rel="noopener">Preview</a>
                        <?php
                        }
=======
                        if (!empty($reports->download_link)) {
                            $previewLink = str_replace('\\', '/', $reports->download_link);

                            if (!preg_match('#^https?://#i', $previewLink)) {
                                if (preg_match('#^[A-Za-z]:/#', $previewLink) === 1 || strpos($previewLink, '/') === 0) {
                                    $previewLink = 'bulk_report/reports/' . basename($previewLink);
                                } else {
                                    $previewLink = preg_replace('#^/?bulk_report/#', 'bulk_report/', $previewLink);
                                    if (strpos($previewLink, 'bulk_report/') !== 0) {
                                        $previewLink = 'bulk_report/' . ltrim($previewLink, '/');
                                    }
                                }

                                $previewLink = base_url($previewLink);
                            }
                            ?>
                            <a href="<?php echo $previewLink; ?>" target="_blank" rel="noopener">Preview</a>
                            /
                            <a href="<?php echo base_url('report/download/'.$reports->id); ?>">Export</a>
                        <?php
                        }

>>>>>>> 808554ff5caea0db9a21de0721b02d4d60db333d
                        ?></td>


			<td style="white-space: nowrap;"><?php echo $reports->generated_time ?></td>

                    <td style="white-space: nowrap;"><?php echo $reports->completed_time ?></td>
			<td style="word-break: break-word;"><?php echo $reports->user ?></td>

			<td style="text-align:center" width="200px">
				<?php 

				echo anchor(site_url('report/delete/'.$reports->id),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"');
				?>
			</td>
		</tr>
                <?php
            }
            ?>
            </tbody>
        </table>
        </div>
        </div>
    </div>
</div>