<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">All generated reports</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="<?php echo base_url('Admin')?>" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <a class="breadcrumb-item" href="#">-</a>
                <span class="breadcrumb-item active">Generated report</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body" style="border: thick #153505 solid;border-radius: 14px;">
        <h2 style="margin-top:0px">Reports List</h2>

        <div class="row m-b-15">
            <div class="col-md-4">
                <label for="generated-report-date">Generated date</label>
                <input type="date" id="generated-report-date" class="form-control" aria-label="Filter reports by generated date">
            </div>
            <div class="col-md-4">
                <label for="generated-report-type">Report type</label>
                <select id="generated-report-type" class="form-control" aria-label="Filter reports by report type">
                    <option value="">All report types</option>
                    <option value="DAILY_LOAN_BOOK">Daily Loan Book</option>
                    <option value="LOAN_BOOK">Loan Book</option>
                    <option value="DAILY_ARREARS_REPORT">Daily Arrears Report</option>
                    <option value="ARREARS_REPORT">Manual Arrears Report</option>
                    <option value="DAILY_PAR_PRINCIPAL_BALANCE">Daily Principal Balance PAR Report</option>
                    <option value="PAR_PRINCIPAL_BALANCE">Manual Principal Balance PAR Report</option>
                    <option value="RISK_RECOVERY_REPORT">Risk Recovery Report</option>
                </select>
            </div>
        </div>

        <div style="width:100%; max-width:100%; overflow-x:auto; overflow-y:hidden;">
        <table class="table table-bordered" id="data-table1" style="margin-bottom: 10px; min-width: 1220px;">
            <thead>
            <tr>
                <th>No</th>
                <th>Report Type</th>
                <th>Status</th>
                <th>progress</th>
                <th>Download Link</th>
                <th>Report Date From</th>
                <th>Report Date To</th>
                <th>Generated Time</th>
                <th>Completed Time</th>

                <th>Generated By</th>

                <th>Action</th>
            </tr>
            </thead>
            <tbody>

          <?php
          $start = 0;
            foreach ($reports_data as $reports)
            {
                $reportTypeDisplay = $reports->report_type;
                if ($reportTypeDisplay === 'DETAILED_PORTFOLIO') {
                    $reportTypeDisplay = 'LOAN_BOOK';
                } elseif ($reportTypeDisplay === 'DAILY_DETAILED_PORTFOLIO') {
                    $reportTypeDisplay = 'DAILY_LOAN_BOOK';
                }
                ?>
                <tr>
			<td width="80px" style="white-space: nowrap;"><?php echo ++$start ?></td>
                    <td style="word-break: break-word;"><?php echo htmlspecialchars($reportTypeDisplay, ENT_QUOTES, 'UTF-8'); ?></td>
                    <td><?php   if($reports->status=='completed'){echo "<font color='green'>Complete</font>";}else{ echo "<font color='red'>In Progress</font>";} ?></td>
                    <td style="min-width: 150px;"><div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: <?php echo $reports->percentage ?>%;" aria-valuenow="<?php echo $reports->percentage ?>" aria-valuemin="0" aria-valuemax="100">

                            </div>
                        </div>
                        <?php echo round($reports->percentage,2) ?>%
                        </td>
                    <td style="white-space: nowrap;"><?php
                        $previewLink = report_preview_url($reports->download_link);
                        if ($previewLink) {
                            ?>
                            <a href="<?php echo htmlspecialchars($previewLink); ?>" target="_blank" rel="noopener">Preview</a>
                        <?php
                        }
                        ?></td>


                    <td style="white-space: nowrap;"><?php echo !empty($reports->report_date_from) ? date('d M Y', strtotime($reports->report_date_from)) : '&mdash;'; ?></td>
                    <td style="white-space: nowrap;"><?php echo !empty($reports->report_date_to) ? date('d M Y', strtotime($reports->report_date_to)) : '&mdash;'; ?></td>

			<td style="white-space: nowrap;"><?php echo $reports->generated_time ?></td>

                    <td style="white-space: nowrap;"><?php echo $reports->completed_time ?></td>
			<td style="word-break: break-word;"><?php echo $reports->user ?></td>

			<td style="text-align:center" width="200px">
				<?php 

				echo anchor(site_url('report/delete/'.$reports->id),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"');
				?>
			</td>
		</tr>
                <?php
            }
            ?>
            </tbody>
        </table>
        </div>
        </div>
    </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var table = document.getElementById('data-table1');
    var dateFilter = document.getElementById('generated-report-date');
    var typeFilter = document.getElementById('generated-report-type');
    if (!table || !dateFilter || !typeFilter) return;

    function applyGeneratedReportFilters() {
        if (window.jQuery && jQuery.fn.dataTable && jQuery.fn.dataTable.isDataTable(table)) {
            var dataTable = jQuery(table).DataTable();
            var escapedType = jQuery.fn.dataTable.util.escapeRegex(typeFilter.value);
            var escapedDate = jQuery.fn.dataTable.util.escapeRegex(dateFilter.value);
            dataTable.column(1).search(escapedType ? '^' + escapedType + '$' : '', true, false);
            dataTable.column(7).search(escapedDate ? '^' + escapedDate : '', true, false).draw();
            return;
        }

        Array.prototype.forEach.call(table.tBodies[0].rows, function (row) {
            var type = row.cells[1].textContent.trim();
            var generatedDate = row.cells[7].textContent.trim().substring(0, 10);
            var matchesDate = !dateFilter.value || generatedDate === dateFilter.value;
            var matchesType = !typeFilter.value || type === typeFilter.value;
            row.style.display = matchesDate && matchesType ? '' : 'none';
        });
    }

    dateFilter.addEventListener('change', applyGeneratedReportFilters);
    typeFilter.addEventListener('change', applyGeneratedReportFilters);

    // The shared footer initializes DataTables on DOM ready. Re-apply after
    // that initialization so pagination and the filters remain in sync.
    window.setTimeout(applyGeneratedReportFilters, 0);
});
</script>
