<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Group_assigned_amount_model extends CI_Model
{

    public $table = 'group_assigned_amount';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('group_assigned_amount.id', $this->order);
        $this->db->select("*,group_assigned_amount.id as gid")
			->from($this->table)
			->join('groups','groups.group_id=group_assigned_amount.group_id')
			->join('employees','employees.id=group_assigned_amount.disbursed_by');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('group_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('approval_comment', $q);
	$this->db->or_like('reject_comment', $q);
	$this->db->or_like('disbursed_by', $q);
	$this->db->or_like('date_disbursed', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('group_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('approval_comment', $q);
	$this->db->or_like('reject_comment', $q);
	$this->db->or_like('disbursed_by', $q);
	$this->db->or_like('date_disbursed', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Group_assigned_amount_model.php */
/* Location: ./application/models/Group_assigned_amount_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-13 18:32:16 */
/* http://harviacode.com */
