<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Group_loan_tracker_model extends CI_Model
{

    public $table = 'group_loan_tracker';
    public $id = 'group_loan_tracker_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function validate($group_id,$customer,$assign_id)
    {
    	$this->db->select("*")->from($this->table);
        $this->db->where('group_id',$group_id);
        $this->db->where('customer_id',$customer);
        $this->db->where('disbursement_id',$assign_id);
        return $this->db->get()->result();
    }
    function validate_trans($assign_id)
    {

    	$this->db->select_sum('amount')->from($this->table);
    	$this->db->where('disbursement_id',$assign_id);
        return $this->db->get()->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('group_loan_tracker_id', $q);
	$this->db->or_like('disbursement_id', $q);
	$this->db->or_like('group_id', $q);
	$this->db->or_like('customer_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('date_added', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('group_loan_tracker_id', $q);
	$this->db->or_like('disbursement_id', $q);
	$this->db->or_like('group_id', $q);
	$this->db->or_like('customer_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('date_added', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Group_loan_tracker_model.php */
/* Location: ./application/models/Group_loan_tracker_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-13 21:19:44 */
/* http://harviacode.com */
