<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Internal_accounts_model extends CI_Model
{

    public $table = 'internal_accounts';
    public $id = 'internal_account_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select("*")->from($this->table)->join('account','account.client_id=internal_accounts.internal_account_id')
			->join('employees','employees.id = internal_accounts.adde_by');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('internal_account_id', $q);
	$this->db->or_like('account_name', $q);
	$this->db->or_like('is_cash_account', $q);
	$this->db->or_like('adde_by', $q);
	$this->db->or_like('date_created', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('internal_account_id', $q);
	$this->db->or_like('account_name', $q);
	$this->db->or_like('is_cash_account', $q);
	$this->db->or_like('adde_by', $q);
	$this->db->or_like('date_created', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Internal_accounts_model.php */
/* Location: ./application/models/Internal_accounts_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-31 08:43:33 */
/* http://harviacode.com */
