<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Loan_products_model extends CI_Model
{

    public $table = 'loan_products';
    public $id = 'loan_product_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->reset_query();
        $this->db->order_by($this->id, $this->order);
        $rows = $this->db->get($this->table)->result();
        return is_array($rows) ? $rows : array();
    }

    /**
     * Loan products for a branch (loan_products.branch stores branches.Code, e.g. 7042, 89).
     */
    function get_by_branch_code($branch_code)
    {
        $this->db->reset_query();
        $this->db->order_by($this->id, $this->order);
        $this->db->where('branch', trim((string)$branch_code));
        $rows = $this->db->get($this->table)->result();
        return is_array($rows) ? $rows : array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('loan_product_id', $q);
	$this->db->or_like('product_name', $q);
	$this->db->or_like('interest', $q);
	$this->db->or_like('added_by', $q);
	$this->db->or_like('date_created', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('loan_product_id', $q);
	$this->db->or_like('product_name', $q);
	$this->db->or_like('interest', $q);
	$this->db->or_like('added_by', $q);
	$this->db->or_like('date_created', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Loan_products_model.php */
/* Location: ./application/models/Loan_products_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-19 05:38:56 */
/* http://harviacode.com */