<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Savings_products_model extends CI_Model
{

    public $table = 'savings_products';
    public $id = 'saviings_product_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select("*")->from($this->table)->join('employees','employees.id = savings_products.added_by');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('saviings_product_id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('added_by', $q);
	$this->db->or_like('date_added', $q);
	$this->db->or_like('interest_per_anum', $q);
	$this->db->or_like('interest_method', $q);
	$this->db->or_like('interest_posting_frequency', $q);
	$this->db->or_like('when_to_post', $q);
	$this->db->or_like('minimum_balance_for_interest', $q);
	$this->db->or_like('minimum_balance_withdrawal', $q);
	$this->db->or_like('overdraft', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('saviings_product_id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('added_by', $q);
	$this->db->or_like('date_added', $q);
	$this->db->or_like('interest_per_anum', $q);
	$this->db->or_like('interest_method', $q);
	$this->db->or_like('interest_posting_frequency', $q);
	$this->db->or_like('when_to_post', $q);
	$this->db->or_like('minimum_balance_for_interest', $q);
	$this->db->or_like('minimum_balance_withdrawal', $q);
	$this->db->or_like('overdraft', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Savings_products_model.php */
/* Location: ./application/models/Savings_products_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-30 22:32:39 */
/* http://harviacode.com */
