<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sytem_date_model extends CI_Model
{

    public $table = 'sytem_date';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_active()
    {
        $this->db->where('is_active', 'Yes');
        return $this->db->get($this->table)->row();
    }
	public function run_end($f){
		$d=$this->db->select('*')->from($this->table)->where('is_active','Yes')->get()->row();

		$datas = array(
			's_date'=>$f,
			'is_active'=>"Yes"
		);
		$data = array(
			'is_active'=>"No"
		);

		$this->db->where('id',$d->id);
		$this->db->update('sytem_date',$data);
		$this->db->insert($this->table,$datas);
		$this->db->where('id','1');
		$this->db->update('day_end_start',array('day_started'=>'No'));
		return true;
	}
    public function start(){
    	$this->db->where('id','1');
    	$this->db->update('day_end_start',array('day_started'=>'Yes'));
	}
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('s_date', $q);
	$this->db->or_like('is_active', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('s_date', $q);
	$this->db->or_like('is_active', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sytem_date_model.php */
/* Location: ./application/models/Sytem_date_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-26 17:09:41 */
/* http://harviacode.com */
