<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Access_model extends CI_Model
{

    public $table = 'access';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function get_all_acces($idd){
        $this->db->order_by($this->id, $this->order);
        $this->db->where('roleid', $idd);
        return $this->db->get($this->table)->result();
    }
    function remove_menu($arr,$data){
        if($arr){
            for($i=0;$i <count($arr);$i++){

                //print_r($arr[$i]);
                //print($data);
                $menu=array(
                    'roleid'=>$data,
                    'controllerid'=>$arr[$i]
                );
                $this->db->select('*');
                $this->db->from('access');
                $this->db->where('roleid',$data);
                $this->db->where('controllerid',$arr[$i]);
                $query=$this->db->get()->row_array();
                if ($query){
                    $this->db->where('id', $query['id']);
                    $this->db->delete('access', $menu);
//                if($query->controllerid==$arr[$i]){
//                    $this->db->where('id', $query['id']);
//                    $this->db->update('access', $menu);
//
//                }else {
//                    $this->db->where('id',$query['id']);
//                    $this->db->delete('access',$menu);
//                }

                }
//                else{
//                    $this->db->insert('access',$menu);
//
//                }
            }
            return true;

        }
        else{
            echo "array not passed";
        }
    }
    function check_menu($arr,$data){
        if($arr){
            for($i=0;$i <count($arr);$i++){

                //print_r($arr[$i]);
                //print($data);
                $menu=array(
                    'roleid'=>$data,
                    'controllerid'=>$arr[$i]
                );
                $this->db->select('*');
                $this->db->from('access');
                $this->db->where('roleid',$data);
                $this->db->where('controllerid',$arr[$i]);
                $query=$this->db->get()->row_array();
                if ($query){
                    $this->db->where('id', $query['id']);
                    $this->db->update('access', $menu);
//                if($query->controllerid==$arr[$i]){
//                    $this->db->where('id', $query['id']);
//                    $this->db->update('access', $menu);
//
//                }else {
//                    $this->db->where('id',$query['id']);
//                    $this->db->delete('access',$menu);
//                }

                }
                else{
                    $this->db->insert('access',$menu);

                }
            }
            return true;

        }
        else{
            echo "array not passed";
        }
    }


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('roleid', $q);
	$this->db->or_like('controllerid', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('roleid', $q);
	$this->db->or_like('controllerid', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Access_model.php */
/* Location: ./application/models/Access_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-09 19:16:50 */
/* http://harviacode.com */